image:
    file: .gitpod.Dockerfile
tasks:
  - name: set permissions in conda area
    before: sudo chmod -R o+w /opt/conda/

  - name: initialize and source conda
    before: conda init bash ; source ~/.bashrc
